# Global VM resource settings
# Configuration can be found here: https://github.com/qemus/qemu
# THIS DOCKER COMPOSE FILE IS USED FOR SETTING UP THE BASE VM ENVIRONMENT
services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "ubuntu" # Default boot image
      # BOOT: "https://releases.ubuntu.com/jammy/ubuntu-22.04.5-desktop-amd64.iso" # Downloads the Spider2-V image
      DEBUG: "Y"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "16G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # NoVNC
      - 2222:22 # SSH
    volumes:
      # UBUNTU NOBLE: Set BOOT to "ubuntu"
      - ${ROOT_DIR}/src/docker/vms/ubuntu-noble:/storage
      # UBUNTU JAMMY: Set BOOT to the URL
      # - ${ROOT_DIR}/src/docker/vms/ubuntu-jammy:/storage
      # SHARED (SCREENSHOT) VOLUME
      # Shared volume - note the leading slash for absolute path
      # - ${ROOT_DIR}/src/docker/shared:/shared
    restart: always
    stop_grace_period: 2m
