# Global VM resource settings
# Configuration can be found here: https://github.com/qemus/qemu
services:
  qemu:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: qemu
    environment:
      BOOT: "ubuntu" # Default boot image
      # BOOT: "https://huggingface.co/datasets/xlangai/ubuntu_osworld/resolve/main/Ubuntu.qcow2.zip" # Downloads the Spider2-V image
      DEBUG: "Y"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "12G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
    volumes:
      # - ${ROOT_DIR}/docker/volumes/ubuntu:/storage # FOR READ ONLY APPEND `:ro`
      - ${ROOT_DIR}/src/docker/vms/ubuntu/boot.iso:/boot.iso
    restart: always
    stop_grace_period: 2m
