# include:
#   - compose.vector-db.yaml

services:
  kasm-ubuntu:
    container_name: kasm-ubuntu
    build:
      context: .
      dockerfile: environment/Dockerfile.kasm
      args:
        BASE_TAG: "develop"
        BASE_IMAGE: "core-ubuntu-noble"
    environment:
      # VNC_PW: password # Directly set the VNC password
      # VNC_RESOLUTION: 1120x1120 # Set the VNC resolution
      SANDBOX_HOST: "0.0.0.0" # Set the sandbox server host
      SANDBOX_PORT: "8765" # Set the sandbox server port
      VNCOPTIONS: -disableBasicAuth
    ports:
      - "6901:6901"
      - "4901:4901"
      - "8765:8765"
    shm_size: "512m"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ${VOLUME_DIRECTORY:-.}/screenshots:/tmp/screenshots
