# Global VM resource settings
# Configuration can be found here: https://github.com/qemus/qemu
services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "ubuntu" # Default boot image
      # BOOT: "https://huggingface.co/datasets/xlangai/ubuntu_osworld/resolve/main/Ubuntu.qcow2.zip" # Downloads the Spider2-V image
      DEBUG: "Y"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "16G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # NoVNC
      - 2222:22 # SSH
    volumes:
      - ${ROOT_DIR}/src/docker/vms/ubuntu:/storage
    restart: always
    stop_grace_period: 2m
