services:
  linux-server-webtop:
    # image: lscr.io/linuxserver/webtop:ubuntu-xfce
    build:
      context: .
      dockerfile: environment/Dockerfile.linuxserver
    container_name: linux-server-webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./config:/config
    # - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    # devices:
    #   - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
